import type { Metadata } from 'next';

import './globals.css';

import Menu from '../components/Menu';
import Header from '../components/layouts/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import styles from './layout.module.scss';
import Period from '../components/Period';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body className={styles.body}>
        <div className={styles.header}>
          <Header />
        </div>

        <div className={styles.main}>
          <Period />
          {children}
        </div>
      </body>
    </html>
  );
}
